### ISSUE TITLE
Missing system and content folders for checksum calculation

### ISSUE THREAD

**Issue by macedot** [DeKugelschieber/acweb#11]
Missing system and content folders for checksum calculation. Should exist at current server folder. Follow log excerpt: 
---
WARNING: Cannot open file  system/data/surfaces.ini  for checksum, the client check will be disabled for this file
Initializing checksum for track config indy
WARNING: Cannot open file  content/tracks/ks_brands_hatch/indy/data/surfaces.ini  for checksum, the client check will be disabled for this file
Calculating checksum for folder content/cars/ks_abarth500_assetto_corse/data
Error calculating checksum: Folder not found

**Comment by DeKugelschieber** [comment]
I merged your pull request and fixed some issues with it. Can you test if this bug still exists and if your new parameters work? To do that, you can pull the latest docker image.

**Comment by macedot** [comment]
Should work now.
i'm still having trouble trying to run acServer with parameters.
I moved ini creating inside /config/<id>, will request a pull by tomorrow.

**Comment by DeKugelschieber** [comment]
Is this working now?

**Comment by macedot** [comment]
Yes it is. :+1:
