### ISSUE TITLE
Calculate sun angle

### ISSUE THREAD

**Issue by DeKugelschieber** [DeKugelschieber/acweb#15]
```
this.time = '08 =00';
```

configuration.js line 189. I added this issue to merge a pending pull request first.

**Comment by venyii** [comment]
What I was wondering: What's the time used for specifically? I tested this with AC's Server Manager, and the time slider only changes the sun angle (-80 to 80 in steps of 30 minutes) from what I could see, but both are configurable in acweb.

A bit of the same question for the realistic road temp. which is also calculated by the Server Manager automatically but configurable in acweb (while there's no actual ini config option for this).

If this is used in Go for something, sorry haven't looked through everything yet :)

**Comment by DeKugelschieber** [comment]
I used the server desktop tool as a template. The frontend does no calculations , so I decided to  add fields for manual configuration. If they're not added to the ini anyway, we can remove them. The time is shown in game, but I have no idea if it has any influence otherwise.

**Comment by venyii** [comment]
Yep the time should only be used to calculate the sun angle option, there's nothing else in the `server_cfg.ini` diff when changing the time. Same for the realistic road temp, this is not a config value, only informational it seems. We should be safe to remove these from the data model and provide a better UI that does the time to sun angle calc. in the background

**Comment by DeKugelschieber** [comment]
Sounds good, we'll wait for #14 to be merged.

**Comment by DeKugelschieber** [comment]
So can we take this into 1.1.0 or should I move it to 1.2.0?

**Comment by venyii** [comment]
When's the release planned? I can rebase the PR and do some last tests, should be good to go without much work I think.

**Comment by DeKugelschieber** [comment]
I don't plan release dates, but it would be cool to do an official release. Take your time.
