### ISSUE TITLE
columns missing from mysql database

### ISSUE THREAD

**Issue by juaniwck** [DeKugelschieber/acweb#3]
schema.sql does not contain the columns `admin`, `moderator` in the user table.
![missing columns](https://cloud.githubusercontent.com/assets/28688550/26035222/a9b17b2e-388e-11e7-921f-4c4d8f9b2c4d.PNG)

**Comment by DeKugelschieber** [comment]
I added the missing columns to the schema.sql. Thanks for your help! :)
