### ISSUE TITLE
Grid for log list

### ISSUE THREAD

**Issue by macedot** [DeKugelschieber/acweb#31]
How about a new look for log list at instance page?
http://w2ui.com/web/demo/grid

**Comment by DeKugelschieber** [comment]
I don't think this works with vuejs?

**Comment by macedot** [comment]
Dunno, maybe they can coexist somehow?
w2ui grid allows search, sort and reduced screen size. When running multiple (3+) server instances, stop-starting, etc, log list start to increase very fast. :)

**Comment by DeKugelschieber** [comment]
VueJs can do all of that too. It just gets messy when adding another library.
