### ISSUE TITLE
can't connect to postgres db

### ISSUE THREAD

**Issue by Rolzzz** [DeKugelschieber/acweb#40]
environment variables set as:

export ACWEB_HOST=0.0.0.0:8080
export ACWEB_LOGDIR=/usr/games/acweb/log/
export ACWEB_LOGLEVEL=debug
export ACWEB_INSTANCE_LOGDIR=instance_logs
export ACWEB_CONFIG_DIR=/usr/games/acweb/config/
export ACWEB_TLS_PRIVATE_KEY=
export ACWEB_TLS_CERT=
export ACWEB_DB_TYPE=postgres
export ACWEB_DB_USER=acweb
export ACWEB_DB_PASSWORD=********
export ACWEB_DB_HOST=127.0.0.1:5432
export ACWEB_DB=acweb
export ACWEB_DB_PORT=5432
export ACWEB_DB_SSLMODE=disable
export ACWEB_DB_SSL_CERT=
export ACWEB_DB_SSL_KEY=
export ACWEB_DB_ROOT_CERT=

error in log as follows

cat 20171024_145442.log
time="2017-10-24T14:54:42+10:00" level=info msg="Connecting to database 'acweb' at '127.0.0.1:5432'"
time="2017-10-24T14:54:42+10:00" level=fatal msg="Error connecting to database" err="default addr for network '127.0.0.1:5432' unknown"

Schema loaded and can manually connect

psql -h localhost -U acweb acweb
psql (9.2.23)
Type "help" for help.
acweb=>

**Comment by DeKugelschieber** [comment]
What version are you using? 1.3.0 is not released yet. Also ACWEB_DB_HOST must not contain the port. Instead of 127.0.0.1 you can use localhost.

**Comment by Rolzzz** [comment]
Using 1.2.1

Tried localhost, with/without port, all same error

**Comment by DeKugelschieber** [comment]
You cannot connect to Postgres from 1.2.1 :) Wait for 1.3.0. I can release it this evening without stracker/minorating support.

**Comment by Rolzzz** [comment]
Ah sorry, I jumped the gun!
Will wait for 1.3.0

Stracker/Minorating is currently secondary... once I can get acweb functional I can investigate exactly what’s needed to get it going.
