### ISSUE TITLE
Can't "save" acweb config via web interface - "Error 1054: Unknown column 'auth_plugin_address' in 'field list'"

### ISSUE THREAD

**Issue by Coradol** [DeKugelschieber/acweb#55]
Hello. I am running acweb and a mysql instance in two docker containers. DB is set, connection between the two hosts is working, i can login to the web frontend, i set the settings AC server folder to /ac,  i put in my linux assetto server into /ac directory on the acweb instance, i ckecked write permissions on the /ac directory.

But when I press the save button in the web frontend, nothing happens. In the logfile an error is raist telling me: time="2018-12-09T17:09:00Z" level=error msg="Error saving configuration" err="Error 1054: Unknown column 'auth_plugin_address' in 'field list'"

Any ideas?

Thanks.

**Comment by Kugelschieber** [comment]
Glad it worked for you :) I should make that more clear probably...
