### ISSUE TITLE
Add ability to add cars and tracks

### ISSUE THREAD

**Issue by KoumaMisna** [DeKugelschieber/acweb#66]
Would be great to have the ability to add cars and tracks via the web interface. I don't want to grant SSH access to my AC server moderators.

**Comment by Kugelschieber** [comment]
I'm working on accweb currently, so I don't add new features to acweb anymore. If you're familiar with Go and Vue/Js, feel free to add it by yourself. You could add a simple textfield for example that contains the json configuration file. Another solution would be to allow your users to access the configuration directory via FTP.
